worker_processes auto;

events {}

http {
	include mime.types;

	server {
		listen 8080;

		# To make Redmine appear as if it's in a subdirectory, change `/` with the
		# path defined in `RAILS_RELATIVE_URL_ROOT`.
		location / {
			proxy_http_version 1.1;
			proxy_pass http://redmine:3000;
			proxy_redirect off;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $http_host;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Host $http_x_forwarded_host;
			proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
			proxy_set_header X-Real-IP $remote_addr;
		}
	}

	server {
		listen 8081;

		location / {
			client_max_body_size 100m;
			proxy_http_version 1.1;
			proxy_pass http://document-server;
			proxy_redirect off;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $http_host;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Host $http_x_forwarded_host;
			proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
			proxy_set_header X-Real-IP $remote_addr;
		}
	}
}
